name: CD - Deploy Bundle

on:
  workflow_run:
    workflows: ["CI - Validate Bundle"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ ONLY THIS (NO pip install)
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      # ✅ Auth
      - name: Configure Auth
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databrickscfg
          echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databrickscfg

      # ✅ Deploy Bundle
      - name: Deploy Bundle
        run: databricks bundle deploy --target dev